home page
VICTORMUHIRE/Portfolio pull request #3
Opened 2024-08-05 08:22 UTC by VICTORMUHIRE

in this branch, we can find the home page of portofolio project

2024-08-05 10:34 UTC, ciraganenicole requested changes
🎊 Congratulations

![Screenshot 2024-08-05 031634](https://github.com/user-attachments/assets/f9ac0215-8ed8-48b3-810a-96b00afbb542)

Il faut centrer le contenu principal

2024-08-05 10:34 UTC, ciraganenicole commented on style.css
> +              }
Supprime cette partie

2024-08-05 11:13 UTC, Hoppy5 requested changes
Hey Victor! congratulation for the work done your code is very clear and well structured. but i have some thing to suggest to you. i think on the button you forgot to put the box shadow. and you have to center the content of your body. 
![Capture d’écran 2024-08-05 131102](https://github.com/user-attachments/assets/434eb379-6153-411f-aa9e-5cd05da6144e)

2024-08-06 12:34 UTC, ciraganenicole approved these changes

2024-08-06 12:37 UTC, Hoppy5 approved these changes

2024-08-06 12:43 UTC, merged